#!/bin/sh

APPDIR=/var/kushidou-touchscreen/desktops
AUTODIR=/etc/xdg/autostart
MENUDIR=/usr/share/applications

# desktop
for USERNAME in $(cat /etc/passwd | awk -F: '$3>=500' | cut -d : -f 1)
do
    if [ $USERNAME == "nobody" ];then
        continue
    fi
    rm /home/$USERNAME/Desktop/touchscreen-config.desktop 
    rm /home/$USERNAME/Desktop/touchscreen-now.desktop
done

# start menu
rm $MENUDIR/touchscreen-config.desktop 
rm $MENUDIR/touchscreen-now.desktop

# autostart
rm $AUTODIR/touchscreen-autoremap.desktop 
rm $AUTODIR/touchscreen-powerup.desktop

#ICOS
rm /usr/share/pixmaps/screen-config.png
rm /usr/share/pixmaps/screen-remap.png

#USR/BIN
rm /usr/bin/screen-remap
rm /usr/bin/screen-setup
