#!/bin/sh



APPDIR=/var/kushidou-touchscreen/desktops
AUTODIR=/etc/xdg/autostart
MENUDIR=/usr/share/applications
BINDIR=/usr/bin

# start menu
cp $APPDIR/touchscreen-config.desktop $MENUDIR
cp $APPDIR/touchscreen-now.desktop $MENUDIR

# desktop
for USERNAME in $(cat /etc/passwd | awk -F: '$3>=500' | cut -d : -f 1)
do
    cp $APPDIR/touchscreen-config.desktop /home/$USERNAME/Desktop
    cp $APPDIR/touchscreen-now.desktop /home/$USERNAME/Desktop
done

# autostart
cp $APPDIR/touchscreen-autoremap.desktop $AUTODIR
cp $APPDIR/touchscreen-powerup.desktop $AUTODIR

#ICOS
cp $APPDIR/*.png /usr/share/pixmaps/

#USR/BIN
ln -s /var/kushidou-touchscreen/remap-screen /usr/bin/screen-remap
ln -s /var/kushidou-touchscreen/setup-screen /usr/bin/screen-setup
